# Generated by Django 3.0.8 on 2020-10-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_name',
            new_name='posted_by',
        ),
    ]

